// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Allowance } from "./tables/Allowance.sol";
import { Grantor } from "./tables/Grantor.sol";
