// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ComputeUnits } from "./tables/ComputeUnits.sol";
import { ComputeUnitManager } from "./tables/ComputeUnitManager.sol";
