// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { NamespaceOwner } from "./tables/NamespaceOwner.sol";
import { UserDelegationControl } from "./tables/UserDelegationControl.sol";
