// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct AllowanceData {
  uint256 allowance;
  address next;
  address previous;
}

library Allowance {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "AllowanceV2", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74620000000000000000000000000000416c6c6f77616e636556320000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0048030020141400000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (address, address)
  Schema constant _keySchema = Schema.wrap(0x0028020061610000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, address, address)
  Schema constant _valueSchema = Schema.wrap(0x004803001f616100000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "user";
    keyNames[1] = "sponsor";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "allowance";
    fieldNames[1] = "next";
    fieldNames[2] = "previous";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get allowance.
   */
  function getAllowance(address user, address sponsor) internal view returns (uint256 allowance) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get allowance.
   */
  function _getAllowance(address user, address sponsor) internal view returns (uint256 allowance) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set allowance.
   */
  function setAllowance(address user, address sponsor, uint256 allowance) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((allowance)), _fieldLayout);
  }

  /**
   * @notice Set allowance.
   */
  function _setAllowance(address user, address sponsor, uint256 allowance) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((allowance)), _fieldLayout);
  }

  /**
   * @notice Get next.
   */
  function getNext(address user, address sponsor) internal view returns (address next) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get next.
   */
  function _getNext(address user, address sponsor) internal view returns (address next) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set next.
   */
  function setNext(address user, address sponsor, address next) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((next)), _fieldLayout);
  }

  /**
   * @notice Set next.
   */
  function _setNext(address user, address sponsor, address next) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((next)), _fieldLayout);
  }

  /**
   * @notice Get previous.
   */
  function getPrevious(address user, address sponsor) internal view returns (address previous) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get previous.
   */
  function _getPrevious(address user, address sponsor) internal view returns (address previous) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set previous.
   */
  function setPrevious(address user, address sponsor, address previous) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((previous)), _fieldLayout);
  }

  /**
   * @notice Set previous.
   */
  function _setPrevious(address user, address sponsor, address previous) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((previous)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(address user, address sponsor) internal view returns (AllowanceData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(address user, address sponsor) internal view returns (AllowanceData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(address user, address sponsor, uint256 allowance, address next, address previous) internal {
    bytes memory _staticData = encodeStatic(allowance, next, previous);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(address user, address sponsor, uint256 allowance, address next, address previous) internal {
    bytes memory _staticData = encodeStatic(allowance, next, previous);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(address user, address sponsor, AllowanceData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.allowance, _table.next, _table.previous);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(address user, address sponsor, AllowanceData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.allowance, _table.next, _table.previous);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint256 allowance, address next, address previous) {
    allowance = (uint256(Bytes.getBytes32(_blob, 0)));

    next = (address(Bytes.getBytes20(_blob, 32)));

    previous = (address(Bytes.getBytes20(_blob, 52)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (AllowanceData memory _table) {
    (_table.allowance, _table.next, _table.previous) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(address user, address sponsor) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(address user, address sponsor) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 allowance, address next, address previous) internal pure returns (bytes memory) {
    return abi.encodePacked(allowance, next, previous);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 allowance,
    address next,
    address previous
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(allowance, next, previous);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(address user, address sponsor) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160(user)));
    _keyTuple[1] = bytes32(uint256(uint160(sponsor)));

    return _keyTuple;
  }
}
