// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAllowanceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAllowanceSystem {
  error AllowanceSystem_InsufficientAllowance(uint256 allowance, uint256 required);
  error AllowanceSystem_NotAuthorized(address caller, address sponsor, address user);
  error AllowanceSystem_NotFound(address user, address sponsor);

  function removeAllowance(address user, address sponsor) external;

  function getAllowance(address user) external view returns (uint256);
}
