// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAllowanceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAllowanceSystem {
  error AllowanceSystem_InsufficientBalance(uint256 balance, uint256 allowance);

  function grantAllowance(address to, uint256 allowance) external payable;

  function removeAllowance(address sponsor, address user) external;
}
