// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBalanceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBalanceSystem {
  error BalanceSystem_BalanceTooHigh(address user, uint256 balance, uint256 max);
  error BalanceSystem_InsufficientBalance(address user, uint256 amount, uint256 balance);

  function depositTo(address to) external payable;

  function withdrawTo(address payable to, uint256 amount) external;
}
