// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IComputeUnitSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IComputeUnitSystem {
  error ComputeUnitSystem_InsufficientAllowance(address manager, uint256 allowance);

  function addComputeUnits(address user, uint256 computeUnits) external;
}
