// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGrantSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGrantSystem {
  error GrantSystem_AllowanceBelowMinimum(uint256 allowance, uint256 min);
  error GrantSystem_AllowancesLimitReached(uint256 length, uint256 max);
  error GrantSystem_InsufficientBalance(uint256 balance, uint256 required);

  function grantAllowance(address user, uint256 allowance) external payable;
}
