// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPassSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPassSystem {
  function registerPass(bytes32, uint256, uint256, uint256) external pure;

  function issuePass(bytes32, address) external pure;

  function claimFor(address, bytes32) external pure;
}
