// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISpenderSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISpenderSystem {
  error SpenderSystem_AlreadyRegistered(address spender, address user);
  error SpenderSystem_HasOwnBalance(address spender);

  function registerSpender(address spender) external;
}
