// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { IAllowanceSystem } from "./IAllowanceSystem.sol";
import { IBalanceSystem } from "./IBalanceSystem.sol";
import { IPaymasterSystem } from "./IPaymasterSystem.sol";
import { ISpenderSystem } from "./ISpenderSystem.sol";
import { IAdminSystem } from "./IAdminSystem.sol";
import { IGrantSystem } from "./IGrantSystem.sol";
import { IPassSystem } from "./IPassSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IAllowanceSystem,
  IBalanceSystem,
  IPaymasterSystem,
  ISpenderSystem,
  IAdminSystem,
  IGrantSystem,
  IPassSystem
{}
